In [1]:
import torch
def activation(x):
    return(1/1+torch.exp(-x))

In [2]:
torch.manual_seed(7)
features = torch.randn(1,5)
weights = torch.randn_like(features)
bias = torch.randn(1)

In [3]:
y = activation(torch.mm(features,weights.view(5,1))+ bias)

In [4]:
torch.manual_seed(7)
fratures = torch.randn(1,5)
ninput = features.shape[1]
hidden = 2
output = 1
W1 = torch.randn(ninput,hidden)
W2 = torch.randn(hidden,output)
B1 = torch.randn(1,hidden)
B2 = torch.randn(1,output)
h = activation(torch.mm(features,W1)+B1)
y = activation(torch.mm(h,W2)+B2)
print(y)

tensor([[1.0007]])


In [5]:
import numpy as np
a = np.random.rand(4,3)
a

array([[0.60609352, 0.77286442, 0.293194  ],
       [0.93250186, 0.97434625, 0.43343959],
       [0.24257097, 0.77274751, 0.48651624],
       [0.26436291, 0.91598044, 0.33437775]])

In [6]:
b = torch.from_numpy(a)
b

tensor([[0.6061, 0.7729, 0.2932],
        [0.9325, 0.9743, 0.4334],
        [0.2426, 0.7727, 0.4865],
        [0.2644, 0.9160, 0.3344]], dtype=torch.float64)

In [7]:
b.numpy()

array([[0.60609352, 0.77286442, 0.293194  ],
       [0.93250186, 0.97434625, 0.43343959],
       [0.24257097, 0.77274751, 0.48651624],
       [0.26436291, 0.91598044, 0.33437775]])

In [8]:
b.mul_(2)

tensor([[1.2122, 1.5457, 0.5864],
        [1.8650, 1.9487, 0.8669],
        [0.4851, 1.5455, 0.9730],
        [0.5287, 1.8320, 0.6688]], dtype=torch.float64)

In [9]:
a

array([[1.21218703, 1.54572884, 0.58638799],
       [1.86500372, 1.94869249, 0.86687917],
       [0.48514193, 1.54549502, 0.97303248],
       [0.52872581, 1.83196088, 0.6687555 ]])